text_settings:
  max_chars_per_chunk: 256
  max_total_chars_streaming: 3000

backbone_configs:
  "VieNeu-TTS (GPU)":
    repo: pnnbao-ump/VieNeu-TTS
    supports_streaming: false
    description: Chất lượng cao nhất, yêu cầu GPU
  "VieNeu-TTS-0.3B (GPU)":
    repo: pnnbao-ump/VieNeu-TTS-0.3B
    supports_streaming: false
    description: Phiên bản nhẹ cho GPU, tốc độ nhanh x2 so với phiên bản gốc 
  "VieNeu-TTS-q8-gguf":
    repo: pnnbao-ump/VieNeu-TTS-q8-gguf
    supports_streaming: true
    description: Phiên bản GGUF có chất lượng cao nhất
  "VieNeu-TTS-q4-gguf":
    repo: pnnbao-ump/VieNeu-TTS-q4-gguf
    supports_streaming: true
    description: Cân bằng giữa chất lượng và tốc độ
  "VieNeu-TTS-0.3B-q4-gguf":
    repo: pnnbao-ump/VieNeu-TTS-0.3B-q4-gguf
    supports_streaming: true
    description: Phiên bản cực nhẹ, chạy mượt trên CPU
  "VieNeu-TTS-0.3B-q8-gguf":
    repo: pnnbao-ump/VieNeu-TTS-0.3B-q8-gguf
    supports_streaming: true
    description: Phiên bản 0.3B nén Q8, chất lượng cao và tốc độ nhanh trên CPU

codec_configs:
  "NeuCodec (Standard)":
    repo: neuphonic/neucodec
    description: Codec chuẩn, tốc độ trung bình
    use_preencoded: false
  "NeuCodec (Distill)":
    repo: neuphonic/distill-neucodec
    description: Codec tối ưu, tốc độ cao
    use_preencoded: false
  "NeuCodec ONNX (Fast CPU)":
    repo: neuphonic/neucodec-onnx-decoder-int8
    description: Tối ưu cho CPU, cần pre-encoded codes
    use_preencoded: true

voice_samples:
  "Tuyên (nam miền Bắc)":
    audio: ./vieneu/assets/samples/Tuyên (nam miền Bắc).wav
    text: ./vieneu/assets/samples/Tuyên (nam miền Bắc).txt
    codes: ./vieneu/assets/samples/Tuyên (nam miền Bắc).pt
  "Vĩnh (nam miền Nam)":
    audio: ./vieneu/assets/samples/Vĩnh (nam miền Nam).wav
    text: ./vieneu/assets/samples/Vĩnh (nam miền Nam).txt
    codes: ./vieneu/assets/samples/Vĩnh (nam miền Nam).pt
  "Bình (nam miền Bắc)":
    audio: ./vieneu/assets/samples/Bình (nam miền Bắc).wav
    text: ./vieneu/assets/samples/Bình (nam miền Bắc).txt
    codes: ./vieneu/assets/samples/Bình (nam miền Bắc).pt
  "Đoan (nữ miền Nam)":
    audio: ./vieneu/assets/samples/Đoan (nữ miền Nam).wav
    text: ./vieneu/assets/samples/Đoan (nữ miền Nam).txt
    codes: ./vieneu/assets/samples/Đoan (nữ miền Nam).pt
  "Ngọc (nữ miền Bắc)":
    audio: ./vieneu/assets/samples/Ngọc (nữ miền Bắc).wav
    text: ./vieneu/assets/samples/Ngọc (nữ miền Bắc).txt
    codes: ./vieneu/assets/samples/Ngọc (nữ miền Bắc).pt
  "Ly (nữ miền Bắc)":
    audio: ./vieneu/assets/samples/Ly (nữ miền Bắc).wav
    text: ./vieneu/assets/samples/Ly (nữ miền Bắc).txt
    codes: ./vieneu/assets/samples/Ly (nữ miền Bắc).pt
  "Will":
    audio: ./vieneu/assets/samples/Will.wav
    text: ./vieneu/assets/samples/Will.txt
    codes: ./vieneu/assets/samples/Will.pt
